### ISSUE TITLE
在页面上注册用户，会弹出“请求错误 500: http://172.18.124.26:8089/api/auth/register”的错误

### ISSUE THREAD

**Issue by solode** [t880216t/IAT#1]
在页面上注册用户，会弹出“请求错误 500: http://172.18.124.26:8089/api/auth/register”的错误。

请问，具体的原因是什么呢？日志打印在哪个路径下呢？

**Comment by t880216t** [comment]
http://172.18.124.26:8089/api/auth/register
这个是你是自己的服务器么，是用docker部署的还是自己编译的呢？docker部署的可以看下docker logs -f xxxx的容器运行日志。目前我没有专门加日志系统。

**Comment by solode** [comment]
> http://172.18.124.26:8089/api/auth/register
> 这个是你是自己的服务器么，是用docker部署的还是自己编译的呢？docker部署的可以看下docker logs -f xxxx的容器运行日志。目前我没有专门加日志系统。

是使用docker部署的，查看了一下docker的日志，应该是连不上本地的MySQL，我按照你文档中描述的安装了mysql，需要做怎样的配置呢？例如用户名或者密码之类的？
OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '127.0.0.1' ([Errno 111] Connection refused)") (Background on this error at: http://sqlalche.me/e/e3q8)
[2019-01-30 02:55:48,718] ERROR in app: Exception on /api/auth/login [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/IAT/server/app/build/login.py", line 21, in login
    data = users.query.filter_by(username=username).first()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2895, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2687, in __getitem__
    return list(res)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2995, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 3016, in _execute_and_instances
    close_with_result=True)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 3025, in _get_bind_args
    **kw
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 3007, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1046, in connection
    execution_options=execution_options)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1051, in _connection_for_bind
    engine, execution_options)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 409, in _connection_for_bind
    conn = bind.contextual_connect()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2123, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2162, in _wrap_pool_connect
    e, dialect, self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception_noconnection
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 400, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 788, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 529, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 1193, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 1190, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 347, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 474, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 671, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/strategies.py", line 106, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 412, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '127.0.0.1' ([Errno 111] Connection refused)") (Background on this error at: http://sqlalche.me/e/e3q8)

**Comment by redbiscuit** [comment]
我也是用docker部署的 明明指定了IP地址 但是还是默认的127.0.0.1 是不是有问题

**Comment by t880216t** [comment]
@solode @redbiscuit  用docker部署的话，需要指定mysql地址的（如果在一台机器上就是宿主机IP）,如下
``` bash
# docker run --env PATH=/root/apache-jmeter-5.0/bin:$PATH  -v /etc/localtime:/etc/localtime:ro -t -i -d -p 8089:80 -p 9022:22 --name=iat ownerworld/iat:0.0.4 /bin/start.sh "root:root@192.168.0.101:3306"
```
确保指定的mysql账号有远程登录权限。

**Comment by redbiscuit** [comment]
docker run --env PATH=/home/apache-jmeter-5.0/bin:$PATH  -v /etc/localtime:/etc/localtime:ro -t -i -d -p 8084:80 -p 9022:22 --name=iat ownerworld/iat:0.0.4 /bin/start.sh "root:root@192.168.2.54:3306"
192.168.2.54 这台确保已经有了远程登陆的权限，但是log里还是127.0.0.1

**Comment by t880216t** [comment]
@redbiscuit  log能贴来看看么

**Comment by redbiscuit** [comment]
![image](https://user-images.githubusercontent.com/10804067/52930936-67674980-3385-11e9-9567-0c5734a1769f.png)

**Comment by redbiscuit** [comment]
![image](https://user-images.githubusercontent.com/10804067/52930968-8665db80-3385-11e9-911f-c01ba0d86fb7.png)

**Comment by t880216t** [comment]
@redbiscuit  不确定是不是sh脚本遇到了什么异常，你可以通过ssh进到docker容器里面看下参数配置是否正确：
### 1.ssh登录docker 容器：
```
$ ssh -p 9022 root@192.168.2.54
```
密码：root
### 2.查看配置信息
```
$ cd /root/IAT/server/app
$ nano __init__.py
```
查看app.config["SQLALCHEMY_DATABASE_URI"] = "mysql+pymysql...."的配置是不是你的。

**Comment by t880216t** [comment]
目前已知在腾讯云Centos下部署，会出现启动脚本命令找不到的异常，建议用Ubuntu。
